### ISSUE TITLE
Bugs and improvements - help

### ISSUE THREAD

**Issue by gsabarinath02** [MetantiConan/LearningPronunciation#10]
Hi Team, 
   
   First, I found this work very impressive and kudos to the developers.

      But when I was trying to run this i was encountered with various small small bugs. so could you guys please help us out in how to run this project. in windows or ubuntu.
      1. which version of python u exactly used and all version of packages u used 
      2. some imports like model, AImodels etc are being used in ur code, where are they exactly, as far as i understood its not a python package that we can install with pip. so could u rectify it by providing the packages and necessary details.
      3. its easy to understand and run if u have a better doccumentation 
      
I would like to give any credits to you if i could improve this and come up with better results 

Thanks

**Comment by MetantiConan** [comment]
### Thank you for your comment!

We are working under difficult conditions (Syria) and with limited resources. We could not implement this project as we wanted and we did not write a usage document, but you can find some instructions in the markdown file.

We used python > 3.8 and the buckeye dataset, but the model we made was not very accurate. We tried to improve it with ASR, but it did not work well. We think the TIMIT dataset would be better for this kind of project, which uses acoustic model recognition. We created the model locally and then pushed it to AWS server, but we could not get all the data back from the program, so we used google API voice speech, which was not very human-like. The model is md5 and it is in the code. We wanted to implement German with a different dataset, but we ran out of time. We hope to make this program work for more languages, especially (English, Arabic, German, Spanish, French, Turkish).

You can read the issues we posted before to see the problems we are facing.

This program runs on windows and Linux (any distro) in the same way.

We appreciate any contribution or suggestion you can offer to improve the result.

**Comment by gsabarinath02** [comment]
Hey, Thank you for your reply and time, I will help u with this.

Firstly, I am a data scientist currently working on a similar project for our organization. The idea is to improve the accent of the people, especially in the English language by giving them continuous feedback. I will be working on this project for the next few months.
Also once we are done with English we will extend it to other languages.
 
It would be great if u could help me and give me some directions, about where u exactly stand now so that I can build upon that and try to improve the model and performance. This will also help us to save a huge amount of time. 

- in models. py corpus_lables and corpus_frames are not defined. could u tell where those come from or how to fix that
- in DataExtraction.py there is a missing import 'cleaneddata' where is it from? or how to get that? In the same file "frame_duration" is not defined

**Comment by ibra-kdbra** [comment]
I will answer in the other issue
